import { z } from "zod";

export const carFormSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  slug: z.string().optional(),
  description: z.string().min(10, "Description must be at least 10 characters"),
  brandName: z.string().min(1, "Brand name is required"),
  categoryId: z.string().uuid("Please select a category"),
  year: z.coerce.number().min(1990).max(new Date().getFullYear() + 2),
  pricePerDay: z.coerce.number().positive("Price must be positive"),
  weekendPricePerDay: z.coerce.number().positive().optional().nullable(),
  weeklyPrice: z.coerce.number().positive().optional().nullable(),
  monthlyPrice: z.coerce.number().positive().optional().nullable(),
  securityDeposit: z.coerce.number().min(0).default(0),
  fuelType: z.enum(["GASOLINE", "DIESEL", "ELECTRIC", "HYBRID", "PLUG_IN_HYBRID"]),
  transmission: z.enum(["AUTOMATIC", "MANUAL", "SEMI_AUTOMATIC"]),
  seats: z.coerce.number().min(2).max(8),
  doors: z.coerce.number().min(2).max(6).default(4),
  color: z.string().min(1, "Color is required"),
  exteriorColor: z.string().optional().nullable(),
  interiorColor: z.string().optional().nullable(),
  mileage: z.coerce.number().min(0),
  licensePlate: z.string().min(1, "License plate is required"),
  vin: z.string().optional().nullable(),
  engineSize: z.string().optional().nullable(),
  horsepower: z.coerce.number().positive().optional().nullable(),
  torque: z.string().optional().nullable(),
  topSpeed: z.string().optional().nullable(),
  zeroToSixty: z.string().optional().nullable(),
  fuelCapacity: z.coerce.number().positive().optional().nullable(),
  trunkCapacity: z.string().optional().nullable(),
  features: z.array(z.string()).default([]),
  status: z.enum(["AVAILABLE", "RESERVED", "RENTED", "MAINTENANCE", "CLEANING", "OUT_OF_SERVICE"]).default("AVAILABLE"),
  isFeatured: z.boolean().default(false),
  isPublished: z.boolean().default(true),
});

export type CarFormData = z.infer<typeof carFormSchema>;

export const carSearchSchema = z.object({
  search: z.string().optional(),
  brandId: z.string().optional(),
  categoryId: z.string().optional(),
  status: z.string().optional(),
  fuelType: z.string().optional(),
  transmission: z.string().optional(),
  minPrice: z.coerce.number().optional(),
  maxPrice: z.coerce.number().optional(),
  year: z.coerce.number().optional(),
  isFeatured: z.coerce.boolean().optional(),
  sort: z.enum(["newest", "oldest", "price-asc", "price-desc", "name-asc", "name-desc"]).optional(),
  page: z.coerce.number().min(1).default(1),
  limit: z.coerce.number().min(1).max(100).default(12),
});
